function getMode(category = "") {
  const value = String(category).toLowerCase();

  if (value.includes("salon") || value.includes("spa")) return "salon";
  if (value.includes("tuition") || value.includes("coaching")) return "education";
  if (value.includes("retail") || value.includes("kirana") || value.includes("boutique")) return "retail";
  if (value.includes("tailor") || value.includes("service")) return "service";
  return "food";
}

const copy = {
  en: {
    food: {
      collectionName: "Menu",
      collectionHeader: "Dishes on Menu",
      collectionAction: "My Menu",
      collectionDescription: "Update items, prices & availability",
      addItem: "Add Food Item",
      addItemTitle: "Add New Dish",
      addItemDescription: "Visible instantly to customers on WhatsApp",
      photoLabel: "Dish Photo",
      itemNameLabel: "Dish Name",
      itemNamePlaceholder: "e.g. Masala Dosa, Egg Curry",
      shortNotePlaceholder: "e.g. Serves 1 · spicy",
      listEmpty: "No food yet. Tap the button below to add your first dish.",
      availabilityOn: "Available to order",
      availabilityOff: "Sold out for now",
      directLabel: "Direct WhatsApp Order",
      customerCta: "Send on WhatsApp",
      customerEmpty: "This kitchen hasn't added dishes yet.",
      customerNoteTitle: "Any note? (Optional)",
      customerNotePlaceholder: "e.g. Less spicy, extra onions, ringing bell",
      customerState: "Kitchen Open",
      heroSubline: "Counter & WhatsApp Digital Store",
      orderListTitle: "Live Orders",
      orderListText: "View incoming and ready orders",
      messageType: "order",
    },
    retail: {
      collectionName: "Catalog",
      collectionHeader: "Items in Catalog",
      collectionAction: "My Catalog",
      collectionDescription: "Update items, price & stock",
      addItem: "Add Product",
      addItemTitle: "Add New Product",
      addItemDescription: "Visible instantly to customers on WhatsApp",
      photoLabel: "Product Photo",
      itemNameLabel: "Product Name",
      itemNamePlaceholder: "e.g. Aashirvaad Atta 5kg",
      shortNotePlaceholder: "e.g. 5kg pack · home delivery",
      listEmpty: "No items yet. Tap the button below to add your first product.",
      availabilityOn: "Available now",
      availabilityOff: "Out of stock",
      directLabel: "Direct WhatsApp Enquiry",
      customerCta: "Send on WhatsApp",
      customerEmpty: "This shop hasn't added items yet.",
      customerNoteTitle: "Any note? (Optional)",
      customerNotePlaceholder: "e.g. need 2 packets, share delivery time",
      customerState: "Shop Open",
      heroSubline: "Counter & WhatsApp shop",
      orderListTitle: "Customer Requests",
      orderListText: "View incoming customer requests",
      messageType: "enquiry",
    },
    salon: {
      collectionName: "Services",
      collectionHeader: "Services",
      collectionAction: "My Services",
      collectionDescription: "Update services, pricing & availability",
      addItem: "Add Service",
      addItemTitle: "Add New Service",
      addItemDescription: "Visible instantly to customers on WhatsApp",
      photoLabel: "Service Photo",
      itemNameLabel: "Service Name",
      itemNamePlaceholder: "e.g. Haircut + Wash",
      shortNotePlaceholder: "e.g. 45 mins · includes wash",
      listEmpty: "No services yet. Tap the button below to add your first service.",
      availabilityOn: "Available to book",
      availabilityOff: "Not available now",
      directLabel: "Direct WhatsApp Booking",
      customerCta: "Book on WhatsApp",
      customerEmpty: "This salon hasn't added services yet.",
      customerNoteTitle: "Preferred time? (Optional)",
      customerNotePlaceholder: "e.g. tomorrow 6:30 pm",
      customerState: "Now Open",
      heroSubline: "Appointments & WhatsApp booking",
      orderListTitle: "Bookings",
      orderListText: "View incoming bookings",
      messageType: "booking",
    },
    education: {
      collectionName: "Courses",
      collectionHeader: "Courses",
      collectionAction: "My Courses",
      collectionDescription: "Update courses, fees & timing",
      addItem: "Add Course",
      addItemTitle: "Add New Course",
      addItemDescription: "Visible instantly to students on WhatsApp",
      photoLabel: "Course Photo",
      itemNameLabel: "Course Name",
      itemNamePlaceholder: "e.g. Class 10 Maths Batch",
      shortNotePlaceholder: "e.g. Mon-Wed · 5 pm batch",
      listEmpty: "No courses yet. Tap the button below to add your first course.",
      availabilityOn: "Open for enquiry",
      availabilityOff: "Admissions closed",
      directLabel: "Direct WhatsApp Enquiry",
      customerCta: "Enquire on WhatsApp",
      customerEmpty: "This institute hasn't added courses yet.",
      customerNoteTitle: "Any question? (Optional)",
      customerNotePlaceholder: "e.g. fees, batch timing, trial class",
      customerState: "Admissions Open",
      heroSubline: "Course list & WhatsApp enquiries",
      orderListTitle: "Leads",
      orderListText: "View incoming student enquiries",
      messageType: "enquiry",
    },
    service: {
      collectionName: "Services",
      collectionHeader: "Services",
      collectionAction: "My Services",
      collectionDescription: "Update services, pricing & availability",
      addItem: "Add Service",
      addItemTitle: "Add New Service",
      addItemDescription: "Visible instantly to customers on WhatsApp",
      photoLabel: "Service Photo",
      itemNameLabel: "Service Name",
      itemNamePlaceholder: "e.g. Alteration / Repair Visit",
      shortNotePlaceholder: "e.g. same-day service · home visit",
      listEmpty: "No services yet. Tap the button below to add your first service.",
      availabilityOn: "Available now",
      availabilityOff: "Not available now",
      directLabel: "Direct WhatsApp Booking",
      customerCta: "Book on WhatsApp",
      customerEmpty: "This business hasn't added services yet.",
      customerNoteTitle: "Any note? (Optional)",
      customerNotePlaceholder: "e.g. visit after 5 pm",
      customerState: "Available on WhatsApp",
      heroSubline: "Service list & WhatsApp booking",
      orderListTitle: "Requests",
      orderListText: "View incoming requests",
      messageType: "booking",
    },
  },
  hi: {
    food: {
      collectionName: "मेन्यू",
      collectionHeader: "मेन्यू में डिशेस",
      collectionAction: "मेरा मेन्यू",
      collectionDescription: "आइटम, कीमत और उपलब्धता बदलें",
      addItem: "फूड आइटम जोड़ें",
      addItemTitle: "नई डिश जोड़ें",
      addItemDescription: "यह तुरंत ग्राहकों को WhatsApp पर दिखेगी",
      photoLabel: "डिश फोटो",
      itemNameLabel: "डिश का नाम",
      itemNamePlaceholder: "जैसे मसाला डोसा, एग करी",
      shortNotePlaceholder: "जैसे 1 व्यक्ति के लिए · स्पाइसी",
      listEmpty: "अभी कोई खाना नहीं है। नीचे बटन दबाकर पहली डिश जोड़ें।",
      availabilityOn: "ऑर्डर के लिए उपलब्ध",
      availabilityOff: "अभी खत्म है",
      directLabel: "सीधा WhatsApp ऑर्डर",
      customerCta: "WhatsApp पर भेजें",
      customerEmpty: "इस किचन ने अभी डिशेस नहीं जोड़ी हैं।",
      customerNoteTitle: "कोई नोट? (वैकल्पिक)",
      customerNotePlaceholder: "जैसे कम मसाला, ज्यादा प्याज, बेल बजाना",
      customerState: "किचन खुला है",
      heroSubline: "काउंटर और WhatsApp डिजिटल स्टोर",
      orderListTitle: "लाइव ऑर्डर्स",
      orderListText: "आने वाले और तैयार ऑर्डर्स देखें",
      messageType: "order",
    },
    retail: {
      collectionName: "कैटलॉग",
      collectionHeader: "कैटलॉग में आइटम",
      collectionAction: "मेरा कैटलॉग",
      collectionDescription: "आइटम, कीमत और स्टॉक बदलें",
      addItem: "प्रोडक्ट जोड़ें",
      addItemTitle: "नया प्रोडक्ट जोड़ें",
      addItemDescription: "यह तुरंत ग्राहकों को WhatsApp पर दिखेगा",
      photoLabel: "प्रोडक्ट फोटो",
      itemNameLabel: "प्रोडक्ट का नाम",
      itemNamePlaceholder: "जैसे आशीर्वाद आटा 5kg",
      shortNotePlaceholder: "जैसे 5kg पैक · होम डिलीवरी",
      listEmpty: "अभी कोई आइटम नहीं है। नीचे बटन दबाकर पहला प्रोडक्ट जोड़ें।",
      availabilityOn: "अभी उपलब्ध",
      availabilityOff: "स्टॉक खत्म",
      directLabel: "सीधा WhatsApp पूछताछ",
      customerCta: "WhatsApp पर भेजें",
      customerEmpty: "इस दुकान ने अभी आइटम नहीं जोड़े हैं।",
      customerNoteTitle: "कोई नोट? (वैकल्पिक)",
      customerNotePlaceholder: "जैसे 2 पैकेट चाहिए, डिलीवरी समय बताएं",
      customerState: "दुकान खुली है",
      heroSubline: "काउंटर और WhatsApp दुकान",
      orderListTitle: "ग्राहक पूछताछ",
      orderListText: "आने वाली पूछताछ देखें",
      messageType: "enquiry",
    },
    salon: {
      collectionName: "सेवाएं",
      collectionHeader: "सेवाएं",
      collectionAction: "मेरी सेवाएं",
      collectionDescription: "सेवा, कीमत और उपलब्धता बदलें",
      addItem: "सेवा जोड़ें",
      addItemTitle: "नई सेवा जोड़ें",
      addItemDescription: "यह तुरंत ग्राहकों को WhatsApp पर दिखेगी",
      photoLabel: "सेवा फोटो",
      itemNameLabel: "सेवा का नाम",
      itemNamePlaceholder: "जैसे हेयरकट + वॉश",
      shortNotePlaceholder: "जैसे 45 मिनट · वॉश शामिल",
      listEmpty: "अभी कोई सेवा नहीं है। नीचे बटन दबाकर पहली सेवा जोड़ें।",
      availabilityOn: "बुकिंग के लिए उपलब्ध",
      availabilityOff: "अभी उपलब्ध नहीं",
      directLabel: "सीधा WhatsApp बुकिंग",
      customerCta: "WhatsApp पर बुक करें",
      customerEmpty: "इस सैलून ने अभी सेवाएं नहीं जोड़ी हैं।",
      customerNoteTitle: "समय बताएं? (वैकल्पिक)",
      customerNotePlaceholder: "जैसे कल शाम 6:30 बजे",
      customerState: "अभी खुला है",
      heroSubline: "अपॉइंटमेंट और WhatsApp बुकिंग",
      orderListTitle: "बुकिंग्स",
      orderListText: "आने वाली बुकिंग्स देखें",
      messageType: "booking",
    },
    education: {
      collectionName: "कोर्स",
      collectionHeader: "कोर्स",
      collectionAction: "मेरे कोर्स",
      collectionDescription: "कोर्स, फीस और टाइमिंग बदलें",
      addItem: "कोर्स जोड़ें",
      addItemTitle: "नया कोर्स जोड़ें",
      addItemDescription: "यह तुरंत छात्रों को WhatsApp पर दिखेगा",
      photoLabel: "कोर्स फोटो",
      itemNameLabel: "कोर्स का नाम",
      itemNamePlaceholder: "जैसे Class 10 Maths Batch",
      shortNotePlaceholder: "जैसे Mon-Wed · 5 pm batch",
      listEmpty: "अभी कोई कोर्स नहीं है। नीचे बटन दबाकर पहला कोर्स जोड़ें।",
      availabilityOn: "पूछताछ के लिए खुला",
      availabilityOff: "एडमिशन बंद",
      directLabel: "सीधा WhatsApp पूछताछ",
      customerCta: "WhatsApp पर पूछें",
      customerEmpty: "इस संस्थान ने अभी कोर्स नहीं जोड़े हैं।",
      customerNoteTitle: "कोई सवाल? (वैकल्पिक)",
      customerNotePlaceholder: "जैसे फीस, बैच टाइमिंग, ट्रायल क्लास",
      customerState: "एडमिशन खुला है",
      heroSubline: "कोर्स लिस्ट और WhatsApp पूछताछ",
      orderListTitle: "लीड्स",
      orderListText: "आने वाली छात्र पूछताछ देखें",
      messageType: "enquiry",
    },
    service: {
      collectionName: "सेवाएं",
      collectionHeader: "सेवाएं",
      collectionAction: "मेरी सेवाएं",
      collectionDescription: "सेवा, कीमत और उपलब्धता बदलें",
      addItem: "सेवा जोड़ें",
      addItemTitle: "नई सेवा जोड़ें",
      addItemDescription: "यह तुरंत ग्राहकों को WhatsApp पर दिखेगी",
      photoLabel: "सेवा फोटो",
      itemNameLabel: "सेवा का नाम",
      itemNamePlaceholder: "जैसे अल्टरेशन / रिपेयर विजिट",
      shortNotePlaceholder: "जैसे same-day service · home visit",
      listEmpty: "अभी कोई सेवा नहीं है। नीचे बटन दबाकर पहली सेवा जोड़ें।",
      availabilityOn: "अभी उपलब्ध",
      availabilityOff: "अभी उपलब्ध नहीं",
      directLabel: "सीधा WhatsApp बुकिंग",
      customerCta: "WhatsApp पर बुक करें",
      customerEmpty: "इस बिजनेस ने अभी सेवाएं नहीं जोड़ी हैं।",
      customerNoteTitle: "कोई नोट? (वैकल्पिक)",
      customerNotePlaceholder: "जैसे शाम 5 बजे के बाद आएं",
      customerState: "WhatsApp पर उपलब्ध",
      heroSubline: "सेवा लिस्ट और WhatsApp बुकिंग",
      orderListTitle: "रिक्वेस्ट्स",
      orderListText: "आने वाली रिक्वेस्ट्स देखें",
      messageType: "booking",
    },
  },
};

export function getBusinessCopy(category, locale = "en") {
  const mode = getMode(category);
  return copy[locale]?.[mode] || copy.en[mode];
}

export function getBusinessMode(category) {
  return getMode(category);
}
